// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC8dsli1DJAsOGf2z4d7kuLcN2LAI4ytIk',
    appId: '1:519682801670:web:469d69a2430c00aecc0387',
    messagingSenderId: '519682801670',
    projectId: 'recipeapp98',
    authDomain: 'recipeapp98.firebaseapp.com',
    storageBucket: 'recipeapp98.appspot.com',
    measurementId: 'G-JWV144WVC3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAy_lUJJ2DLSzE3e1F5bJTxo6yBUh7h2QU',
    appId: '1:519682801670:android:aa10e373f97f1d4ccc0387',
    messagingSenderId: '519682801670',
    projectId: 'recipeapp98',
    storageBucket: 'recipeapp98.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCU4gqnvXXnISjzR-lWpJMTsnOLrM2SA9s',
    appId: '1:519682801670:ios:bba2cb5bb57c94a4cc0387',
    messagingSenderId: '519682801670',
    projectId: 'recipeapp98',
    storageBucket: 'recipeapp98.appspot.com',
    iosBundleId: 'com.example.recipe',
  );
}
